configuration :
  - name : master
    ip : 127.0.0.1
    port : 12345  
  - name : alice
    ip : 127.0.0.1
    port : 12346
  - name : bob
    ip : 127.0.0.1
    port : 15640
  - name : FileServer
    ip : 127.0.0.1
    port : 15217

mappercnt : 5
reducercnt : 2

split_line_number : 10
mr_home : 
