configuration :
  - name : master
    ip : 127.0.0.1
    port : 12345  
  - name : alice
    ip : 127.0.0.1
    port : 12346
  - name : FileServer
    ip : 127.0.0.1
    port : 15217

mappercnt : 5
reducercnt : 2
masterlogfile : master_log.txt
slavelogfile : slave_log.txt

